title = "Angelica Gardner"

[params.author]
  name = "Angelica Gardner"
  image = "img/profile.jpg"
  headline = "Hello, world!"
  bio = "Backend developer with agile leadership experience."
  links = [
    { github = "https://github.com/angelicagardner" },
    { linkedin = "https://linkedin.com/in/angelica-gardner" }
  ]