[[main]]
  pre = "heart-empty"
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  pre = "code"
  name = "Resum√©"
  pageRef = "resume"
  weight = 20

[[main]]
  pre = "circle-info"
  name = "Download Resume"
  url = "/resume_angelicahjelmgardner.pdf"
  weight = 30
  [main.params]
    target = "_blank"
    rel = "noopener"

[[main]]
  pre = "envelope"
  name = "Contact"
  pageRef = "contact"
  weight = 40

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy"
  weight = 10

[[footer]]
  name = "LeetCode Profile"
  url = "https://leetcode.com/u/angelicahjelmgardner/"
  weight = 20
  [footer.params]
    target = "_blank"
    rel = "noopener"
