[[main]]
  pre = "heart-empty"
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  pre = "code"
  name = "LeetCode Profile"
  url = "https://leetcode.com/u/angelicahjelmgardner/"
  weight = 20

[[main]]
  pre = "circle-info"
  name = "Download Resume"
  url = "/resume_angelicahjelmgardner.pdf"
  weight = 30

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy"
